name:                enum-categorical-digraphs
version:             0.1.0.0
github:              "michaeljklein/enum-categorical-digraphs"
license:             BSD3
author:              "Michael J. Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "(c) 2018 Michael J. Klein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaeljklein/enum-categorical-digraphs#readme>

dependencies:
- base >= 4.7 && < 5
- matrix
- containers
- transformers
- mtl

library:
  source-dirs: src

executables:
  enum-categorical-digraphs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - enum-categorical-digraphs

tests:
  enum-categorical-digraphs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - enum-categorical-digraphs
